//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;


public class ChemMapEarthBehavior : MonoBehaviour
{
	public Transform m_Camera;
	public GameObject halo;
	public AudioSource beep;
	public GameObject gotoText;
	float timer = 0f;
	void FixedUpdate(){

		Ray ray = new Ray (m_Camera.position, m_Camera.rotation * Vector3.forward);
		RaycastHit[] hits = Physics.RaycastAll( ray.origin, ray.direction );
		bool lit = false;
		foreach (RaycastHit hit in hits) {
			//if(hit.transform == transform){
				lit = true;
				break;
			//}
		}

		halo.SetActive (lit);
		if (timer == 0 && lit) {
			beep.Play();
			gotoText.gameObject.SetActive(true);
				}
		if (lit == false) {
			beep.Stop();
			gotoText.gameObject.SetActive(false);
				}
		if(lit)timer+=Time.deltaTime;
		else timer = 0;

		if(timer > 4f)GetComponent<KeyboardHandler>().ProcessBlackout();
	}
}